platform :ios, '9.0'

target 'Im Ready!' do
  use_frameworks!

  # Pods for Im Ready!
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftyJSON'
  pod 'Alamofire-SwiftyJSON'

  target 'Im Ready!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Im Ready!UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
