# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Im Ready!' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Im Ready!
#  pod 'HideShowPasswordTextField', :git => 'https://github.com/Guidebook/HideShowPasswordTextField'

  target 'Im Ready!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Im Ready!UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
