namespace ImReadyApiv2.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ForeignKeys : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Activity", "ComponentId", "dbo.Component");
            DropForeignKey("dbo.Component", "BuildingblockId", "dbo.Buildingblock");
            DropForeignKey("dbo.UsefulLink", "ComponentId", "dbo.Component");
            DropForeignKey("dbo.ClientBuildingBlock", "BuildingblockId", "dbo.Buildingblock");
            DropForeignKey("dbo.ClientComponent", "ClientBuildingBlockId", "dbo.ClientBuildingBlock");
            DropForeignKey("dbo.ClientActivity", "ClientComponentId", "dbo.ClientComponent");
            DropForeignKey("dbo.ClientComponent", "TaskId", "dbo.ClientTask");
            DropForeignKey("dbo.Feedback", "ClientActivityId", "dbo.ClientActivity");
            DropIndex("dbo.Activity", new[] { "ComponentId" });
            DropIndex("dbo.Component", new[] { "BuildingblockId" });
            DropIndex("dbo.UsefulLink", new[] { "ComponentId" });
            DropIndex("dbo.ClientBuildingBlock", new[] { "BuildingblockId" });
            DropIndex("dbo.ClientComponent", new[] { "ClientBuildingBlockId" });
            DropIndex("dbo.ClientComponent", new[] { "TaskId" });
            DropIndex("dbo.ClientActivity", new[] { "ClientComponentId" });
            DropIndex("dbo.Feedback", new[] { "ClientActivityId" });
            DropPrimaryKey("dbo.Activity");
            DropPrimaryKey("dbo.Component");
            DropPrimaryKey("dbo.Buildingblock");
            DropPrimaryKey("dbo.UsefulLink");
            DropPrimaryKey("dbo.ClientBuildingBlock");
            DropPrimaryKey("dbo.ClientComponent");
            DropPrimaryKey("dbo.ClientActivity");
            DropPrimaryKey("dbo.Feedback");
            DropPrimaryKey("dbo.ClientTask");
            AddColumn("dbo.ClientComponent", "ComponentId", c => c.String(maxLength: 128));
            AddColumn("dbo.ClientActivity", "ActivityId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Activity", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Activity", "ComponentId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Component", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Component", "BuildingblockId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Buildingblock", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UsefulLink", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UsefulLink", "ComponentId", c => c.String(maxLength: 128));
            AlterColumn("dbo.ClientBuildingBlock", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ClientBuildingBlock", "BuildingblockId", c => c.String(maxLength: 128));
            AlterColumn("dbo.ClientComponent", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ClientComponent", "ClientBuildingBlockId", c => c.String(maxLength: 128));
            AlterColumn("dbo.ClientComponent", "TaskId", c => c.String(maxLength: 128));
            AlterColumn("dbo.ClientActivity", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ClientActivity", "ClientComponentId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Feedback", "Id", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Feedback", "ClientActivityId", c => c.String(maxLength: 128));
            AlterColumn("dbo.ClientTask", "Id", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.Activity", "Id");
            AddPrimaryKey("dbo.Component", "Id");
            AddPrimaryKey("dbo.Buildingblock", "Id");
            AddPrimaryKey("dbo.UsefulLink", "Id");
            AddPrimaryKey("dbo.ClientBuildingBlock", "Id");
            AddPrimaryKey("dbo.ClientComponent", "Id");
            AddPrimaryKey("dbo.ClientActivity", "Id");
            AddPrimaryKey("dbo.Feedback", "Id");
            AddPrimaryKey("dbo.ClientTask", "Id");
            CreateIndex("dbo.Activity", "ComponentId");
            CreateIndex("dbo.Component", "BuildingblockId");
            CreateIndex("dbo.UsefulLink", "ComponentId");
            CreateIndex("dbo.ClientBuildingBlock", "BuildingblockId");
            CreateIndex("dbo.ClientComponent", "ClientBuildingBlockId");
            CreateIndex("dbo.ClientComponent", "ComponentId");
            CreateIndex("dbo.ClientComponent", "TaskId");
            CreateIndex("dbo.ClientActivity", "ClientComponentId");
            CreateIndex("dbo.ClientActivity", "ActivityId");
            CreateIndex("dbo.Feedback", "ClientActivityId");
            AddForeignKey("dbo.ClientActivity", "ActivityId", "dbo.Activity", "Id");
            AddForeignKey("dbo.ClientComponent", "ComponentId", "dbo.Component", "Id");
            AddForeignKey("dbo.Activity", "ComponentId", "dbo.Component", "Id");
            AddForeignKey("dbo.Component", "BuildingblockId", "dbo.Buildingblock", "Id");
            AddForeignKey("dbo.UsefulLink", "ComponentId", "dbo.Component", "Id");
            AddForeignKey("dbo.ClientBuildingBlock", "BuildingblockId", "dbo.Buildingblock", "Id");
            AddForeignKey("dbo.ClientComponent", "ClientBuildingBlockId", "dbo.ClientBuildingBlock", "Id");
            AddForeignKey("dbo.ClientActivity", "ClientComponentId", "dbo.ClientComponent", "Id");
            AddForeignKey("dbo.ClientComponent", "TaskId", "dbo.ClientTask", "Id");
            AddForeignKey("dbo.Feedback", "ClientActivityId", "dbo.ClientActivity", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Feedback", "ClientActivityId", "dbo.ClientActivity");
            DropForeignKey("dbo.ClientComponent", "TaskId", "dbo.ClientTask");
            DropForeignKey("dbo.ClientActivity", "ClientComponentId", "dbo.ClientComponent");
            DropForeignKey("dbo.ClientComponent", "ClientBuildingBlockId", "dbo.ClientBuildingBlock");
            DropForeignKey("dbo.ClientBuildingBlock", "BuildingblockId", "dbo.Buildingblock");
            DropForeignKey("dbo.UsefulLink", "ComponentId", "dbo.Component");
            DropForeignKey("dbo.Component", "BuildingblockId", "dbo.Buildingblock");
            DropForeignKey("dbo.Activity", "ComponentId", "dbo.Component");
            DropForeignKey("dbo.ClientComponent", "ComponentId", "dbo.Component");
            DropForeignKey("dbo.ClientActivity", "ActivityId", "dbo.Activity");
            DropIndex("dbo.Feedback", new[] { "ClientActivityId" });
            DropIndex("dbo.ClientActivity", new[] { "ActivityId" });
            DropIndex("dbo.ClientActivity", new[] { "ClientComponentId" });
            DropIndex("dbo.ClientComponent", new[] { "TaskId" });
            DropIndex("dbo.ClientComponent", new[] { "ComponentId" });
            DropIndex("dbo.ClientComponent", new[] { "ClientBuildingBlockId" });
            DropIndex("dbo.ClientBuildingBlock", new[] { "BuildingblockId" });
            DropIndex("dbo.UsefulLink", new[] { "ComponentId" });
            DropIndex("dbo.Component", new[] { "BuildingblockId" });
            DropIndex("dbo.Activity", new[] { "ComponentId" });
            DropPrimaryKey("dbo.ClientTask");
            DropPrimaryKey("dbo.Feedback");
            DropPrimaryKey("dbo.ClientActivity");
            DropPrimaryKey("dbo.ClientComponent");
            DropPrimaryKey("dbo.ClientBuildingBlock");
            DropPrimaryKey("dbo.UsefulLink");
            DropPrimaryKey("dbo.Buildingblock");
            DropPrimaryKey("dbo.Component");
            DropPrimaryKey("dbo.Activity");
            AlterColumn("dbo.ClientTask", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Feedback", "ClientActivityId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Feedback", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientActivity", "ClientComponentId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientActivity", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientComponent", "TaskId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientComponent", "ClientBuildingBlockId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientComponent", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientBuildingBlock", "BuildingblockId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClientBuildingBlock", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.UsefulLink", "ComponentId", c => c.Guid(nullable: false));
            AlterColumn("dbo.UsefulLink", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Buildingblock", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Component", "BuildingblockId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Component", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Activity", "ComponentId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Activity", "Id", c => c.Guid(nullable: false));
            DropColumn("dbo.ClientActivity", "ActivityId");
            DropColumn("dbo.ClientComponent", "ComponentId");
            AddPrimaryKey("dbo.ClientTask", "Id");
            AddPrimaryKey("dbo.Feedback", "Id");
            AddPrimaryKey("dbo.ClientActivity", "Id");
            AddPrimaryKey("dbo.ClientComponent", "Id");
            AddPrimaryKey("dbo.ClientBuildingBlock", "Id");
            AddPrimaryKey("dbo.UsefulLink", "Id");
            AddPrimaryKey("dbo.Buildingblock", "Id");
            AddPrimaryKey("dbo.Component", "Id");
            AddPrimaryKey("dbo.Activity", "Id");
            CreateIndex("dbo.Feedback", "ClientActivityId");
            CreateIndex("dbo.ClientActivity", "ClientComponentId");
            CreateIndex("dbo.ClientComponent", "TaskId");
            CreateIndex("dbo.ClientComponent", "ClientBuildingBlockId");
            CreateIndex("dbo.ClientBuildingBlock", "BuildingblockId");
            CreateIndex("dbo.UsefulLink", "ComponentId");
            CreateIndex("dbo.Component", "BuildingblockId");
            CreateIndex("dbo.Activity", "ComponentId");
            AddForeignKey("dbo.Feedback", "ClientActivityId", "dbo.ClientActivity", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClientComponent", "TaskId", "dbo.ClientTask", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClientActivity", "ClientComponentId", "dbo.ClientComponent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClientComponent", "ClientBuildingBlockId", "dbo.ClientBuildingBlock", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ClientBuildingBlock", "BuildingblockId", "dbo.Buildingblock", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UsefulLink", "ComponentId", "dbo.Component", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Component", "BuildingblockId", "dbo.Buildingblock", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Activity", "ComponentId", "dbo.Component", "Id", cascadeDelete: true);
        }
    }
}
